### ISSUE TITLE
[bug] Not Installing in Ubuntu LTS 24

### ISSUE THREAD

**Issue by AI-human** [ZacharyL2/KeyEcho#37]
### OS

Linux

### OS Version

LTS 24

### Describe the bug

Fronted issue

**Comment by hiSandog** [comment]
This would be easier to keep fixed with a clean-environment reproduction that starts from a fresh checkout/cache and runs the documented install or build path. Capturing the exact versions plus the command that fails around `_No` would make it clear whether the fix is in dependency resolution, generated files, or the build configuration.

**Comment by ZacharyL2** [comment]
KeyEcho 1.0 rebuilt the Linux release pipeline and now ships new DEB and RPM packages. This report does not include the installation command, package name, or error log, so there is not enough information to diagnose the old-version failure. I am going to close it for now. If v1 still fails to install on Ubuntu 24.04, please open a new issue with the downloaded filename, the exact `apt` or `dpkg` command, and the full terminal output.
